name: Dispatch WebGUI Build

on:
  release:
    types: [published]

jobs:
  notify-webgui:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch to WebGUI
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Abasz/ESPRowingMonitor-WebGUI
          event-type: esp-rowing-monitor-release
          client-payload: '{"tag": "${{ github.ref_name }}"}'